### ISSUE TITLE
Regreso desde asignatura

### ISSUE THREAD

**Issue by fefrati** [GrupoETICUndec/etic#7]
Cuando se está examinando una asignatura y se desea regresar al plan de estudios, el usuario presiona el botón "Retroceder" del navegador. Sin embargo, en lugar de mostrar el plan, la página muestra la descripción de la carrera. Debería mostrar el plan de estudios para mejorar la experiencia de uso del sitio.

**Comment by smarevalo** [comment]
Boton agregado
